### ISSUE TITLE
new experimental tool term: RNAi resistant

### ISSUE THREAD

**Issue by gm119** [FlyBase/flybase-controlled-vocabulary#126]
request for the following new FBcv term:

[Term]
id: FBcv:NEW
name: RNAi resistant
namespace: experimental_tool_descriptor
def: "Transgenic locus or modified endogenous locus that has been modified so that it is resistant to an RNAi reagent that targets the gene product encoded by the transgenic locus or modified endogenous locus. This is achieved by introducing synonymous nucleotide mutations into the region that would normally be targeted by the RNAi reagent, destroying the target site without altering the amino acid sequence of the encoded gene product." [FBC:GM]
is_a: FBcv:0005001 ! experimental tool descriptor

_(I'm not sure whether 'destroyed' too strong in the description ?!, but could not think of a better wording)_

**Comment by Clare72** [comment]
I think it is clear what is meant.

This should probably have a noun rather than an adjective as the name, so maybe we should append 'allele', 'locus', 'sequence' or similar?

Would this not fit better under 'allele class' than 'experimental tool descriptor' or maybe 'in vitro construct - site-directed mutagenesis'? I am not sure that an RNAi resistant allele really qualifies as a tool as it just has the normal function of the gene.

**Comment by gm119** [comment]
It was helpful discussing this on the VC today - thanks ! Your comment that the RNAi resistance is a property of the sequence, rather than a description of a tool helped me understand better the problem with putting this under 'experimental tool descriptor'. So I agree, lets not put this in the FBcv, but instead hopefully we can get 'RNAi resistant sequence' added in SO instead where it will fit better.
