### ISSUE TITLE
Tritium-related terms under 'ionising radiation'

### ISSUE THREAD

**Issue by sjm41** [FlyBase/flybase-controlled-vocabulary#135]
Currently we have:
```
ionizing radiation
           |__3H (25 rec.)
           |__3H-deoxycytidine (6 rec.)
           |__3H-thymidine (13 rec.)
```

That is, these three '3H' terms are sister terms.

I'm wondering if "3H-deoxycytidine" (aka 'tritiated deoxycytidine') and "3H-thymidine" (aka 'tritiated thymidine') should either (i) be made children of "3H" (aka 'tritium') or (ii) just be merged into "3H"?

AFAIK, using "3H-deoxycytidine" or "3H-thymidine" is just a way of exposing flies to tritium, and thus beta particle radiation - the chemical incorporating the tritium isn't that important. (http://hps.org/documents/tritium_fact_sheet.pdf)
What do you think @Clare72 @gm119?

(The number of annotations here are so low as to almost make all this irrelevant....but I'm trying to align our mutagen -> radiation types with that used by other MODS, notably ZECO.  I think it's worth requesting/integrating '3H/tritium', but not convinced about the other two terms...) 

Also see #134

**Comment by Clare72** [comment]
Ideally everone would be using CHEBI for chemical terms (or maybe ENVO for some radiation terms), but if that is not an option, perhaps everyone should be trying to align with CHEBI, rather than alligning with each other's chemical ontologies?
Surely it will be better for the Alliance to use CHEBI and ENVO than import all the MOD-specific versions.

Regarding this specific question, I am happy to obsolete 3H-deoxycytidine and 3H-thymidine if @gm119 is happy.

**Comment by sjm41** [comment]
Everyone is using CHEBI for chemical terms - I didn't think radiochemical were in CHEBI....?  I'll have to check.

We looked for existing radiation ontologies but didn't find any, so thought to align on using the radiation terms within ZECO (since it's already been decided to use that within the Alliance).  I'll also have a look at ENVO.

Thanks.

**Comment by gm119** [comment]
I agree with Clare's comments about CHEBI and ENVO.

I just checked using OLS and CHEBI already has tritiated thymidine (http://purl.obolibrary.org/obo/CHEBI_53526 ) under a parent 'tritiated compound' term.

I would prefer if we did not get rid of 3H-deoxycytidine and 3H-thymidine if possible (I am wondering if the mutagenic effects might potentially be different if a fly is treated with a tritiated nucleoside (that can maybe get incorporated directly into the DNA ??) vs some other form of tritium which might not get so 'close' (I'm figuring thats why we've got these different terms, but just guessing !)

Since it looks like we can use/request an existing CHEBI term for 3H-deoxycytidine and 3H-thymidine I'd rather we used those instead of deleting (or use an ENVO term if its more appropriate).

**Comment by Clare72** [comment]
there is a slight difference between us and CHEBI, in that we are talking about the radiation from 3H, rather than 3H itself, but I think it is probably close enough to map to the CHEBI term - ultimately it IS 3H that is causing the mutation, and probably better to align as much as possibe to CHEBI.

ENVO has terms for 'radiation', 'ionizing radiation', 'gamma-ray radiation' etc.

**Comment by sjm41** [comment]
Yes, using/adding these radiochemicals to chebi makes sense.
I see that 32-P is also in chebi.
I don't see any of these in ENVO (it has 'alpha particle' and 'gamma ray radiation', but nothing relating to beta radiation...not sure if that's an omission or a considered decision)  

So...these 3 tritium-related radiochemicals and 32-P should be in FBcv under 'chemical (FBcv:0000525)' as well as/instead of under 'irradiation' (FBcv:0000503), right?

**Comment by Clare72** [comment]
If we REALLY want them to repesent radiation, I could give them logical definitions of something like "radiation" and "produced by" some "tritium atom"
But I am not sure that this is necessary for our use case - it is probably sufficient to say that the mutation was caused by the chemical rather than radiation produced by the chemical.

**Comment by Clare72** [comment]
so, yeah, we could move the radiochemicals to "chemical" instead of "irradiation"

**Comment by sjm41** [comment]
_we could move the radiochemicals to "chemical" instead of "irradiation"_
That makes sense to me and will make it easier to harmonise at the Alliance.
And it's consistent with these things being in CHEBI but absent from ENVO.

Here are the 4 terms and their xrefs:
3H (FBcv:0000511) = tritium atom (CHEBI_29238)
3H-deoxycytidine (FBcv:0000512) = [not in CHEBI]
3H-thymidine (FBcv:0000513) = tritiated thymidine (CHEBI_53526)
32P (FBcv:0000510) = phosphorus-32 atom (CHEBI_37972)

I think they should probably be a direct child of our 'chemical (FBcv:0000525)'.

**Comment by sjm41** [comment]
PS. Has anyone yet tried to systematically add CHEBI mappings to our FBcv chemical branch?

**Comment by dosumis** [comment]
Yes.  They should mostly be mapped.  Maybe you're not looking at the editor's file?

**Comment by Clare72** [comment]
Many of our chemical terms are mapped to CHEBI terms already. It is not obvious when you look at FBcv in FlyBase, but most of the definitions and some relationships on these terms are from CHEBI (and are updated each release).

For example, if you look at [1,4-dimethanesulfonoxy-1,4-dimethylbutane on OLS](https://www.ebi.ac.uk/ols/ontologies/fbcv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBcv_0000563) you can see its FBcv parent 'alkylating agent' and its CHEBI parent 'methanesulfonate ester'

This is because '1,4-dimethanesulfonoxy-1,4-dimethylbutane' is asserted to be equivalent to the CHEBI term 'dimethylmyleran' (CHEBI:67107) in FBcv

This was all done some time ago - before me! So it is possible that additional mappings can now be made from FBcv to CHEBI (e.g. for these radiochemical terms)

**Comment by sjm41** [comment]
FYI: Further discussion within the Alliance allele WG agreed that we should treat radiochemical mutagens as chemical mutagens (harmonising on the Chebi IDs). So please go ahead with the plan above to move these 4 terms within FBcv (and adding CHEBI xrefs, where available):

3H (FBcv:0000511) = tritium atom (CHEBI_29238)
3H-deoxycytidine (FBcv:0000512) = [not in CHEBI]
3H-thymidine (FBcv:0000513) = tritiated thymidine (CHEBI_53526)
32P (FBcv:0000510) = phosphorus-32 atom (CHEBI_37972)

I think they should probably be a direct child of our 'chemical (FBcv:0000525)'.

**Comment by sjm41** [comment]
@Clare72 @dosumis 
_They should mostly be mapped. Maybe you're not looking at the editor's file?_

_Many of our chemical terms are mapped to CHEBI terms already. It is not obvious when you look at FBcv in FlyBase, but most of the definitions and some relationships on these terms are from CHEBI (and are updated each release).
For example, if you look at 1,4-dimethanesulfonoxy-1,4-dimethylbutane on OLS you can see its FBcv parent 'alkylating agent' and its CHEBI parent 'methanesulfonate ester'_

I guess I was expecting to see the CHEBI xref for this example (CHEBI:67107) in the "External Crossreferences & Linkouts" section here: https://flybase.org/cgi-bin/cvreport.pl?rel=is_a&id=FBcv:0000563 - that is, to see it as an xref entry in the obo file, rather than just as a reference in the definition/synonyms line.

id: FBcv:0000563
name: 1,4-dimethanesulfonoxy-1,4-dimethylbutane
namespace: origin_of_mutation
def: "A methanesulfonate ester that is hexane-2,5-diol in which the hydrogens of the hydroxy groups are replaced by methanesulfonyl groups." [CHEBI:67107]
synonym: "1,4-dimethanesulfonoxy-1:4-dimethylbutane" RELATED []
synonym: "CB2348" RELATED []
synonym: "dimethylmyleran" RELATED [CHEBI:67107]
synonym: "mutation induced by 1,4-dimethanesulfonoxy-1,4-dimethylbutane exposure" EXACT []
is_a: FBcv:0000526 ! alkylating agent

Looking just now, I don't see any entries in the obo file like "xref: CHEBI:".  Is there a reason for this?

**Comment by Clare72** [comment]
>Looking just now, I don't see any entries in the obo file like "xref: CHEBI:". Is there a reason for this

If you look at the [editors' file](https://github.com/FlyBase/flybase-controlled-vocabulary/blob/master/src/ontology/fbcv-edit.obo#L45), you will see that the CHEBI terms are asserted as being equivalent to our FBcv terms, which means that relationships on the CHEBI terms will be used when reasoning FBcv. If you look at the [equivalent FBcv term](https://github.com/FlyBase/flybase-controlled-vocabulary/blob/master/src/ontology/fbcv-edit.obo#L3502), you will see that the term definition is $sub_CHEBI:13941 - which results in the definition being pulled from CHEBI during the release process, and CHEBI:13941 is the reference for the definition.

We do not have xrefs of the type you describe on these terms. Based on discussions at the recent [WSBO workshop](https://github.com/OntoloBridge/WSBO/) the community hopes to be able to move away from these traditional xrefs (as it is not always clear if the mapping is 1:1 and what the provenance is), so I would be reluctant to add these at this stage when the mappings are already specified in an arguably better way.
