### ISSUE TITLE
Assertions about "part of" contradict BFO world view.

### ISSUE THREAD

**Issue by matentzn** [FlyBase/flybase-controlled-vocabulary#14]
As I outlined in https://github.com/FlyBase/flybase-controlled-vocabulary/issues/13, I am trying to work on integrating phenotype patterns across species ontologies. DPO/FBCV makes the fundamental assertion that "part_of" is a sub-object property of "happens_during". I understand that this is part of another design pattern you are using (shortcut relations), but it would make things easier if this assertion was to be removed (it renders almost 60% of the phenotype classes unsatisfiable when the union of phenotype ontologies is considered), which makes querying across all phenotype ontologies hard. Since happens_during has a domain and range of occurrent, and many continuants use the part of relation (both are disjoint), many phenotypes are inferred to be both occurrents and continuants -> unsatifiable.

**Comment by matentzn** [comment]
Respectful chase :)

**Comment by temjones** [comment]
Hi Nico, until FlyBase recruit their new ontologist (which should be fairly soon), there is no-one currently actively working on FBcv. Any edits before this happens are dependent on me having the free time to devote to them. I'll try to look at this if I can, but I can't promise anything right now, unfortunately!

**Comment by dosumis** [comment]
Hi Tamsin,

Thanks for keeping an eye on tickets here.  I've been discussing this one with Nico. I think we have a temporary fix and a potential longer term one that requires some discussion with FlyBase.  Will post shortly.

**Comment by dosumis** [comment]
Hmmm... This may be tricky to fix. I'm pretty sure that removing that axiom would break some critical inferred classification on lethal phase phenotypes.  

The basic problem:  FBdv uses part_of to link life-cycle phases to stages and stages to substages.  The lethal phase phenotype pattern uses part_of -> happens_during link for temporal reasoning.

Example here:
![image](https://user-images.githubusercontent.com/112839/35629877-a8de67b6-0697-11e8-943c-c971746ccc6b.png)

RO_0002092 = happens_during.

This problem would we fixed if we switched the pattern for lethal phase phenotype terms AND FBdv to use happens_during in place of 'part of'.  I think we need to check with FlyBase whether that would break anything before implementing.  Another possible fix is to switch to using local identifiers for happens_during.  I initially thought this would be a good temp fix, but have now realised we;d have to change all temporal relations in this way (see reasoning chains in explanation above).  So, I think dropping part_of here and in FBdv is the best solution.

More broadly, this points to a general issue with BFO/RO that could only be fixed by having separate part_of relations for continutant and occurrent.

**Comment by dosumis** [comment]
@ggrumbli @gm119   One fix for this issue is to switch all part_of in FBdv and on the lethal phase terms -> 'happens during'.  But I don't want to do this without checking whether it will break things in FlyBase pipeline or on the FlyBase site. One thing I'm worried about specifically:  IIRC Andy wrote a Perl script (or modified one of mine) to automatically generates TAP statements with intermediate stages where the original had a TAP statement had a range.  I believe this uses part_of and so would have to be updated.

**Comment by gm119** [comment]
It is entirely possible that changing all 'part_of' in FBdv to happens_during will break one or more things in the FlyBase pipeline. So we definitely need to get developer input before changes are made to the ontology.

Dave - is the TAP script you are thinking of one that derives statements for the web from data in chado ?

It sounds like you may also be considering changes relationships in FBcv too since your example involves the lethal terms ? so there might be consequences there too.

I think that the way forward is for you to make a detailed spec of the changes and then I can make a ticket in the FlyBase JIRA system for the developers to assess what the issues might be (a similar issue has just come up with switching the version of the DO obo file we use, and that is what the developers requested). Is it possible to make files (FBcv ?? FBdv ??)  with the changes in for the developers to use in testing (**but keeping the 'master' file as is for now until we know whether the changes will break things**) ?

**Comment by Clare72** [comment]
I think this was fixed by adding substage_of to FBdv - lethal patterns now using this instead of part_of
