### ISSUE TITLE
NTR: lead ion sensor

### ISSUE THREAD

**Issue by sjm41** [FlyBase/flybase-controlled-vocabulary#158]
**Def:**
Sequence that forms all or part of the gene product encoded by a transgenic locus or modified endogenous locus and that is used to provide a readout of lead ion concentration.

**Refs:**
Background: PMID: 22240981
Fly usage: PMID: 32204388, 32892119

**Parent:**
small molecule sensor FBcv:0005045

**Comment by gm119** [comment]
although we could make this FBcv term, I've deliberately not been requesting specific FBcv terms for each new type of small molecule sensor (as the list is potentially very long), but instead for now am using the parent 'small molecule sensor FBcv:0005045' term in curation. I think a better long-term option would be to expand FB curation of these sensors so that we could instead combine the 'small molecule sensor' term with the appropriate 'chemical' name in each case as needed (this is now technically possible as we can generate FBch features, would require a change in the way data is stored inthe appropriate tool fields).

So e.g. for this example we would use something like the following curation:

small molecule sensor | lead ion
(where _lead ion_ would be an FBch feature made with links to correct ChEBI term etc),

or e.g. for the _Pyronic_ or _PyronicSF_ sensors:

small molecule sensor | pyruvate

and at that point we'd get rid of the 'calcium ion sensor' term and use small molecule sensor | calcium ion

So I'd favour **not** making this new term, but using small molecule sensor for now and working on getting the curation model enhanced instead.

**Comment by Clare72** [comment]
@sjm41,  I agree with Gillian that this list of small molecule sensors could get very long very quickly and it will probably be more efficient to link to the FBch (and therefore also to ChEBI) terms via curation.
