### ISSUE TITLE
is_a cycles in ontology

### ISSUE THREAD

**Issue by janelomax** [FlyBase/flybase-controlled-vocabulary#161]
fbcv has a number of cyclic classes e.g.  http://purl.obolibrary.org/obo/CHEBI_46790 and  http://purl.obolibrary.org/obo/FBcv_0000570 are subclasses of each other, causing issues in downstream apps. 

Are you likely to resolve these at some point? Or would we be better making a local fix?

**Comment by Clare72** [comment]
Since these terms refer to the same chemical (in this case '2-methoxyethanol'), we assert them to be equivalent.
The additional subClassOf axioms may be due to an issue with redundancy stripping - #77
I don't think this will be changed soon, so it might be better for you to fix what you need to at your end, or use a version with no imported terms (fbcv-simple.owl).

**Comment by janelomax** [comment]
Okay, we'll use fbcv-simple.owl instead I think.
