### ISSUE TITLE
QC: add ISBN wellformed check in chado load script test

### ISSUE THREAD

**Issue by matentzn** [FlyBase/flybase-controlled-vocabulary#63]
DPO and FBCV

**Comment by gouttegd** [comment]
@matentzn Is this issue still relevant?

Looking at the `src/scripts/chado_load_checks.pl` script, there is some code in place to perform some checks on ISBN cross-references, but it is entirely commented out. Should that be re-activated?

**Comment by matentzn** [comment]
I dont remember, feel free to do so, but feel free to also just close.

**Comment by gouttegd** [comment]
OK, I think I know why the check was commented out. It flags several ISBNs that are well-formed but that are still in the old “ISBN-10” format. But they all come from the GO import, not from us. I guess someone got tired of seeing warnings about things that are not ours to fix…

I’ll reactivate the check, but in such a way that it will only flag _ill-formed_ ISBNs, not _old_ ISBNs. That is, it will accept both ISBN-10 and ISBN-13 as long as they are valid, instead of accepting only ISBN-13.

**Comment by dosumis** [comment]
Would be great if we could support this more generally on ODK with SPARQL .

**Comment by gouttegd** [comment]
I don’t think it can be done solely with SPARQL. Verifying that a ISBN is correct implies to compute a checksum on the digits, it doesn’t look like something that can be done with SPARQL’s limited numerical functions.

But of course it should still be possible to use SPARQL to extract ISBN cross-references and then hand them over to a dedicated ISBN validation script.
