### ISSUE TITLE
New qualifier for indicating functional/circuit phenotypes in neurons

### ISSUE THREAD

**Issue by dosumis** [FlyBase/flybase-controlled-vocabulary#80]
It is currently not possible to distinguish between morphological and functional/circuit phenotypes in phenotypic class statements.  Being able to do so would be useful to VFB (this was originally discussed early in the current VFB grant cycle - but seems to have never made it into a ticket).

This could potentially be achieved by add qualifiers to PC statements. 

e.g. we might have the qualifier `circuit phenotype` for cases where manipulating that activity of one neuron changes the activity of another.

**Comment by Clare72** [comment]
How about this as a first draft?:
**label:** 'circuit phenotype'
**is_a:** 'cell non-autonomous'
**def:** 'A phenotypic effect that is apparent in a cell that is downstream in a circuit with the cell that is being experimentally manipulated.'
**comment:** 'This qualifier is usually used for experiments where one type of neuron is conditionally activated and a change in activity is measured in another type that was not directly activated.'

Outstanding questions:
 - do we want to limit this to neurons or neurons and their inputs/outputs (e.g. muscle) or allow any cell types (e.g. hormonal signalling)?
 - do we want to limit this to short-term conditional manipulations (rather than saying messing up development of cell X messes up the downstream cells)?
 - do we want to restrict this to qualifying the 'neurophysiology defective' phenotype?

**Comment by gouttegd** [comment]
@dosumis Is this still relevant?

**Comment by dosumis** [comment]
unfortunately not.
